### ISSUE TITLE
Using 'verifyaccesstoken' middleware with one or all scopes

### ISSUE THREAD

**Issue by ghost** [arietimmerman/laravel-middleware-oauth2-introspect#1]
I'm wondering if it's possible to utilize the included middleware similar to the way Laravel Passport's `scope` and `scopes` middleware work.

With Passport, the following examples are given in the [Laravel Passport Documentation](https://laravel.com/docs/master/passport#token-scopes):

```php
Route::get('/orders', function () {
    // Access token has both "check-status" and "place-orders" scopes...
})->middleware('scopes:check-status,place-orders');
```

```php
Route::get('/orders', function () {
    // Access token has either "check-status" or "place-orders" scope...
})->middleware('scope:check-status,place-orders');
```

With this package, it appears that the scopes defined on a route are treated as all required, as in the first Passport example above. Is it possible for the middleware to check scopes like the second Passport example, and if so, how could we go about implementing this?

**Comment by arietimmerman** [comment]
It took a while, but I've just introduced this as a new feature.

~~~.php
protected $routeMiddleware = [
    // [..]
    'verifyaccesstoken' => \ArieTimmerman\Laravel\OAuth2\VerifyAccessToken::class,
    // Or
    'verifyaccesstoken_has_any' => \ArieTimmerman\Laravel\OAuth2\VerifyAccessTokenHasAnyScope::class,
    // [..]   
];
~~~
