### ISSUE TITLE
Invalid configuration reference string in VerifyAccessToken.php

### ISSUE THREAD

**Issue by kkignatov** [arietimmerman/laravel-middleware-oauth2-introspect#3]
Hi,

Thank you for the nice library! It works well but as of the last commit the string references to the authorization server config in VerifyAccessToken.php are incorrect. Lines 84 and 85 currently read:

'client_id' => config('authorizationserver.authorization_serverclient_id'),
'client_secret' => config('authorizationserver.authorization_serverclient_secret'),

but they should be:

'client_id' => config('authorizationserver.authorization_server_client_id'),
'client_secret' => config('authorizationserver.authorization_server_client_secret'),

It looks like the find/replace was used to change the private $_client variable's name to $client which also removed the underscore of the config reference strings. It would be great to fix this little issue!

**Comment by arietimmerman** [comment]
Thanks for reporting. Now it's fixed.
